### ISSUE TITLE
Add looking at things

### ISSUE THREAD

**Issue by dekarrin** [dekarrin/tunaq#28]
Make it so you can LOOK AT anyfin with a description. in addition, make new key on `[[room]]`:

```toml
[[room]]
label = "SAMPLE"
name = "Sample room"
description = "You are in SAMPLE. there's a TABLE in the middle of it."

[[room.detail]]
aliases = ["TABLE", "TABLE IN MIDDLE"]
description = '''
An ornate table that you feel like has been here for centuries.
'''
```

Allowing you to LOOK AT TABLE, for instance
